defmodule AshLearning.Repo.Migrations.AddUserIdentityFields do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:user_identities) do
      add :email, :text
      add :avatar_url, :text
      add :provider_name, :text
    end
  end

  def down do
    alter table(:user_identities) do
      remove :provider_name
      remove :avatar_url
      remove :email
    end
  end
end
